spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default
    username: sa
    password: sa
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        hbm2ddl:
          auto: none
    show-sql: true
    open-in-view: false

